// Simple script to write src/app/version.ts with the package.json version
const fs = require('fs');
const path = require('path');

const root = __dirname + '/../';
const pkgPath = path.resolve(root, 'package.json');
const outDir = path.resolve(root, 'src/app');
const outFile = path.resolve(outDir, 'version.ts');

try {
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  const version = pkg.version || '';
  const content = `// Auto-generated by tools/write-version.js\nexport const APP_VERSION = '${version}';\n`;
  fs.writeFileSync(outFile, content, 'utf8');
  console.log(`[version] Wrote ${outFile} with version ${version}`);
} catch (err) {
  console.error('[version] Failed to write version file:', err);
  process.exit(1);
}
